#class Details
type classDetails {
  _id: ID!
  name: String!
  standard: String!
  section: String!
  updatedAt: DateTime!
  createdAt: DateTime!
}

#create class Input
input CreateClassInput {
  name: String!
  standard: String!
  section: String!
}

type Query {
  #class Query
  classes: [classDetails]
  class(_id: ID!): classDetails
}

type Mutation {
  #class Mutation
  createClass(input: CreateClassInput!): classDetails
  updateClass(_id: ID!,input: CreateClassInput): classDetails
  deleteClass(_id: ID!): classDetails
}
